config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root 'sales#new'
    
    resources :marks
    resources :categories
    resources :articles do
        resources :historics, only: [:index]
    end
    resources :providers
    resources :stocks, only: [:index]
    resources :sales, only: [:new, :create, :index, :show]
    scope 'admin', as: 'admin' do
      resources :users, except: [:new, :create]
    end
    # Update prices for providers (in mass).
    get 'update_prices', to: 'articles#update_prices'
    post 'update_prices', to: 'articles#update_prices_post'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/mark.rb
class Mark < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error

    validates :name, presence: true
    validates_uniqueness_of :name
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]
  before_action :authorized_admin

  # GET /marks
  def index
    @q = Mark.ransack(params[:q])
    @marks = @q.result.paginate(:page => params[:page]).order(:name)
  end

  # GET /marks/1
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html {
            flash[:success] = 'La marca se ha creado correctamente.'
            redirect_to @mark
        }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html {
            flash[:success] = 'La marca se ha actualizado correctamente.'
            redirect_to return_to_previous_url
        }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  def destroy
    respond_to do |format|
        if @mark.destroy
            format.html {
                flash[:success] = 'La marca se ha creado correctamente.'
                redirect_to marks_url
            }
            format.json { head :no_content }
        else
            format.html {
                flash[:alert] = "No se puede eliminar la marca porque tiene artículos asociados."
                redirect_to marks_url
            }
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:name)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.erb
<%= simple_form_for(@mark) do |f| %>
    <div class="container col-md-6 col-md-offset-3">
        <%= f.error_notification %>

        <div class="form-group">
            <%= f.input :name, autofocus: true %>
        </div>
        <div class="pull-right">
            <%= link_to 'Marcas', marks_path, class: "btn btn-default" %>
            <%= f.button :submit, class: "btn btn-success" %>
        </div>
    </div>

<% end %>

app/views/marks/edit.html.erb
<h3 class="text-center">Editar marca</h3>
<hr>
<%= render 'form', mark: @mark %>

app/views/marks/index.html.erb
<div class="container-fluid">
    <%= render "layouts/search_form", search: :name_cont %>
</div>
<hr>

<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong class="text-center">Marcas</strong>
        <div class="pull-right">
          <div class="btn-right">
            <%= link_to 'Nueva marca', new_mark_path, class: "btn btn-success btn-xs" %>
          </div>
        </div>
      </div>
      <table class="table table-condensed table-bordered table-hover">
      <thead class="">
        <tr>
          <th class="text-center" style="width: 75%"><%= sort_link(@q, :name, default_order: :desc) %></th>
          <th class="text-center" style="width: 25%">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @marks.each do |mark| %>
          <tr>
            <td><%= mark.name %></td>
            <td class="text-center">
                <%= link_to '', mark, class:'glyphicon glyphicon-eye-open btn btn-xs btn-default', title: 'Ver' %>
                <%= link_to '', edit_mark_path(mark), class:'glyphicon glyphicon-pencil btn btn-xs btn-default', title: 'Editar' %>
                <%= link_to '', mark, class:'glyphicon glyphicon-trash btn btn-xs btn-danger', method: :delete, data: { confirm: '¿Estás seguro que quieres eliminar el elemento?' }, title: 'Borrar' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>

    <br>
    <%= render "layouts/pagination", collection: @marks %>
</div>

app/views/marks/new.html.erb
<h3 class="text-center">Nueva marca</h3>
<hr>
<%= render 'form', mark: @mark %>

app/views/marks/show.html.erb
<div class="container col-md-4 col-md-offset-4">
  <div class="container-fluid">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        <b class="text-center">Información de la marca</b>
      </div>
      <div class="panel-body">
        <p>
          <strong>Nombre:</strong>
          <%= @mark.name %>
        </p>
      </div>
    </div>
    <div class="pull-right">
      <%= link_to 'Nueva marca', new_mark_path, class: "btn btn-primary" %>
      <%= link_to 'Editar', edit_mark_path(@mark), class: "btn btn-success" %>
      <%= link_to 'Marcas', marks_path, class: "btn btn-default" %>
    </div>
  </div>
</div>