config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root 'sales#new'
    
    resources :marks
    resources :categories
    resources :articles do
        resources :historics, only: [:index]
    end
    resources :providers
    resources :stocks, only: [:index]
    resources :sales, only: [:new, :create, :index, :show]
    scope 'admin', as: 'admin' do
      resources :users, except: [:new, :create]
    end
    # Update prices for providers (in mass).
    get 'update_prices', to: 'articles#update_prices'
    post 'update_prices', to: 'articles#update_prices_post'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :category
    belongs_to :mark
    has_one :stock, inverse_of: :article, dependent: :destroy
    has_many :historics, dependent: :destroy, inverse_of: :article
    has_many :sale_lines, dependent: :restrict_with_error
    has_many :sales, through: :sale_lines
    has_many :article_providers, dependent: :destroy, inverse_of: :article
    has_many :providers, through: :article_providers

    accepts_nested_attributes_for :article_providers, allow_destroy: true
    accepts_nested_attributes_for :stock, reject_if: :all_blank
    validates_presence_of :stock
    # accepts_nested_attributes_for :historics, reject_if: :all_blank
    # validates_presence_of :historics, on: :create
    validates :code, :name, :cost_price, :percentage, :mark_id, :category_id, presence: true
    validates :cost_price, numericality: { greater_than_or_equal_to: 0 }
    validates :final_price, numericality: { greater_than_or_equal_to: 0 }
    validates :percentage, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    validates :code, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates_uniqueness_of :code

    def create_historic(new_cost_price)
        self.historics.create({cost_price: new_cost_price})
    end

    def last_update_price()
      self.historics.last.created_at
    end

    private
        # Convierto codigo en string para poder buscar en Ransack usando LIKE de SQL.
        ransacker :code do
            Arel.sql("CONVERT(#{table_name}.code, CHAR(14))")
        end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :set_return_to_previous_url, only: [:show, :edit, :update_prices, :index]
    before_action :authorized_admin, except: [:index]
    helper ArticlesHelper

    def index
        respond_to do |format|
            format.html {
                @q = Article.ransack(params[:q])
                @articles  = @q.result.includes(:mark, :category).page(params[:page]).order(:name)
            }
            format.json {
                # En formato JSON, verifico si se realiza consulta por el código de barra (usado en el index de Sales),
                # sino es así, retorno todos los artículos como se hiciera por defecto. ¿Es esta la mejor solución?
                if not params[:q].nil?
                    @article = Article.find_by(code: params[:q])
                    if @article.nil?
                        render json: {errors: :not_found!}, status: :unprocessable_entity
                    else
                        @article
                    end
                else
                    @articles = get_articles
                end
            }
            format.pdf {
              @articles = get_articles
            }
        end
    end

    def show
    end

    def new
        @article = Article.new
        @article.build_stock
        @providers = Provider.all
        @article.article_providers.build
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            @article.create_historic params.require(:article)[:cost_price]
            flash[:success] = 'El artículo se ha creado exitosamente.'
            redirect_to @article
        else
            render :edit
        end
    end

    def update
        @old_cost_price = @article.cost_price
        @old_percentage = @article.percentage
        @old_final_price = @article.final_price
        if @article.update(article_params)
            # @article.historics.create!({cost_price: params.require(:article)[:cost_price], article_id: @article.id})
            if article_prices_changed?
                @article.create_historic params.require(:article)[:cost_price]
            end
            flash[:success] = 'El artículo se ha actualizado correctamente.'
            redirect_to return_to_previous_url
        else
            render :edit
        end
    end

    def destroy
        if @article.destroy
            flash[:success] = 'El artículo se ha borrado correctamente.'
        else
            flash[:alert] = 'Hubo errores al intentar borrar artículo.'
        end
        redirect_to articles_url
    end

    # GET /update_prices
    def update_prices
        @articles = get_articles
    end

    # POST /update_prices
    def update_prices_post
        percentage = params[:percentage].to_f
        ids_array = params[:article_id]
        ids_array.each do |id|
          a = Article.find(id)
          old_price = a.cost_price
          a.cost_price = ( old_price * percentage / 100 ) + old_price
          final_price = (a.cost_price * a.percentage / 100) + a.cost_price
          a.final_price = final_price.round
          a.save
          # Creamos el histórico de precios
          if old_price != a.cost_price
              a.create_historic(a.cost_price)
          end
        end
        length = ids_array.length
        flash[:success] = "Los precios de los #{length} productos se han actualizado correctamente."
        redirect_to return_to_previous_url
    end

    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:name, :cost_price, :percentage, :description,
                                    :mark_id, :category_id, :code, :final_price,
                                    article_providers_attributes: [:id, :article_id, :provider_id, :_destroy],
                                    stock_attributes: [:id, :article_id, :current_amount, :minimum_amount])
        end

        def article_prices_changed?
          if @old_cost_price != @article.cost_price or @old_percentage != @article.percentage or @old_final_price != @article.final_price
            true
          else
            false
          end
        end

        def get_articles
          @q = Article.ransack(params[:q])
          @q.result.includes(:mark, :category).order(:name)
        end

end

app/helpers/articles_helper.rb
module ArticlesHelper
    def get_providers(article_id)
        Article.find(article_id).providers
    end

    def get_category_name(category_id)
        Category.find(category_id).name
    end

    def get_mark_name(mark_id)
        Mark.find(mark_id).name
    end

    def get_final_price(article_id)
      if not article_id.nil?
        ActionController::Base.helpers.number_with_precision(Article.find(article_id).final_price, precision: 2, separator: '.')
      end
    end

    def get_cost_price(article_id)
      if not article_id.nil?
        ActionController::Base.helpers.number_with_precision(Article.find(article_id).cost_price, precision: 2, separator: '.')
      end
    end
end

app/views/articles/_article_search_form.html.erb
<div class="container-fluid">
    <div class="pull-right">
        <%= search_form_for @q, html: {class: "form-inline"} do |f| %>
            <%= f.search_field :code_or_description_or_name_cont, class: "form-control", placeholder: "Buscar", onclick: 'this.select();' %>
            <%= f.collection_select :mark_id_eq, Mark.order(:name), :id, :name, {prompt: "Seleccione marca", include_blank: true}, {class: "form-control"} %>
            <%= f.collection_select :category_id_eq, Category.order(:name), :id, :name, {prompt: "Seleccione categoría", include_blank: true}, {class: "form-control"} %>
            <%= f.collection_select :providers_id_eq, Provider.order(:name), :id, :name, {prompt: "Seleccione proveedor", include_blank: true}, {class: "form-control"} %>
            <%= f.submit "Buscar", class: "btn btn-default" %>
        <% end %>
    </div>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
    <div class="row">
        <div class="container col-md-6">
            <%= f.error_notification %>
            <div class="form-group">
                <%= f.input :code, input_html: { onfocusout: current_page?(new_article_url @article) ? "checkIfExistArticle();" : "", autofocus: true, min: 0 }%>
            </div>
            <div class="form-group">
                <%= f.input :name %>
            </div>
            <div class="form-group">
                <%= f.input :cost_price, input_html: {value: get_cost_price(@article.id) || 0, min: 0, onkeyup: 'calculateFinalPrice(this);'} %>
            </div>
            <div class="form-group">
                <%= f.input :percentage, input_html: {value: @article.percentage || 0, min: 0, onkeyup: 'calculateFinalPrice(this);'} %>
            </div>
            <div class="form-group">
                <%= f.input :final_price, input_html: {value: get_final_price(@article.id) || 0, min: 0} %>
            </div>
        </div>
        <div class="container col-md-6">
            <div class="form-group">
                <%= f.input :description %>
            </div>
            <div class="form-group">
                <%= f.input :mark_id, :collection => Mark.all.order(:name).collect { |m| [ m.name, m.id ] }, as: :select %>
            </div>
            <div class="form-group">
                <%= f.input :category_id, :collection => Category.order(:name).all.collect { |c| [ c.name, c.id ] }, as: :select %>
            </div>
            <%# Nested fields for stock %>
            <%= f.fields_for :stock do |ff| %>
                <div class="form-group">
                    <%= ff.input :current_amount, as: :numeric, input_html: {value: @article.stock.current_amount || 0, min: 0} %>
                </div>
                <div class="form-group">
                    <%= ff.input :minimum_amount, as: :numeric, input_html: {value: @article.stock.minimum_amount || 0, min: 0} %>
                </div>
                <%= ff.hidden_field :id %>
                <%= ff.hidden_field :article_id %>
            <% end %>
        </div>
    </div>
    <%# Nested fields for providers %>
    <div class="row">
        <div class="col-md-6 form-inline">
            <%= f.nested_fields_for :article_providers do |pp| %>
                <%= pp.input :provider_id, :collection => Provider.order(:name).all.collect {|p| [p.name, p.id] }, label: "Proveedor", as: :select %>
                <%= pp.hidden_field :id %>
                <%= pp.hidden_field :article_id %>
                <%= pp.remove_nested_fields_link 'Eliminar proveedor', class: "btn btn-danger", data: { confirm: "¿Estás seguro que quieres eliminar este proveedor?"}, onclick: 'removeRequire(this);' %>
            <hr>
            <% end %>
        </div>
        <div class="col-md-6">
            <%= f.add_nested_fields_link :article_providers, "Agregar proveedor", class: "btn btn-success" %>
        </div>
    </div>
    <div class="pull-right">
        <%= link_to 'Artículos', articles_path, class: "btn btn-default" %>
        <%= f.button :submit, class: "btn btn-success" %>
    </div>

<% end %>

<%= render 'modal_new_article' %>

app/views/articles/_modal_new_article.html.erb
<!-- Modal information -->
<div class="modal fade" id="modalCheck" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-center">Información:</h4>
      </div>
      <div class="modal-body">
        <h3>Ya existe un producto con el mismo código de barra.</h3>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Volver</button>
      </div>
    </div>
    <!-- End modal content -->
  </div>
</div>
<!-- End modal confirmation-->

app/views/articles/edit.html.erb
<h3 class="text-center">Editar artículo</h3>
<hr>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<%= render 'article_search_form' %>
<hr>
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Artículos</strong>
        <div class="pull-right">
            <div class="btn-right">
                <%= link_to 'Nuevo artículo', new_article_path, class: "btn btn-success btn-xs" %>
            </div>
        </div>
      </div>
        <table class="table table-condensed table-bordered table-hover">
          <thead class="">
            <tr>
              <th class="text-center"><%= sort_link(@q, :code) %></th>
              <th class="text-center"><%= sort_link(@q, :name, default_order: :desc) %></th>
              <th class="text-center"><%= sort_link(@q, :description) %></th>
              <th class="text-center"><%= sort_link(@q, :mark_name, "Marca") %></th>
              <th class="text-center"><%= sort_link(@q, :final_price) %></th>
              <th class="text-center">Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% @articles.each do |article| %>
            <tr>
              <td><%= article.code %></td>
              <td><%= article.name %></td>
              <td style="text-overflow:ellipsis;overflow:hidden;white-space:nowrap"><%= article.description %></td>
              <td><%= get_mark_name(article.mark_id) %></td>
              <td>$ <%= get_final_price(article.id) %></td>
              <td class="text-center">
                <%= link_to '', article, class:'glyphicon glyphicon-eye-open btn btn-xs btn-default', title: 'Ver' %>
                <%= link_to '', edit_article_path(article), class:'glyphicon glyphicon-pencil btn btn-xs btn-default', title: 'Editar' %>
                <%= link_to '', article, class:'glyphicon glyphicon-trash btn btn-xs btn-danger', method: :delete, data: { confirm: '¿Estás seguro que quieres eliminar el elemento?' }, title: 'Borrar' %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <% if @articles.length > 0 %>
      <% if not params[:q].nil? %>
        <%= link_to 'Ver en PDF', articles_path(:format => :pdf, utf8: params[:utf8], :'q[code_or_description_or_name_cont]' => params[:q]['code_or_description_or_name_cont'], :'q[mark_id_eq]' => params[:q]['mark_id_eq'], :'q[category_id_eq]' => params[:q]['category_id_eq'], :'q[providers_id_eq]' => params[:q]['providers_id_eq']), class:'btn btn-xs btn-info pull-right', title: 'PDF', target: '_blank' %>
        <%= link_to 'Actualizar precios', update_prices_path(utf8: params[:utf8], :'q[code_or_description_or_name_cont]' => params[:q]['code_or_description_or_name_cont'], :'q[mark_id_eq]' => params[:q]['mark_id_eq'], :'q[category_id_eq]' => params[:q]['category_id_eq'], :'q[providers_id_eq]' => params[:q]['providers_id_eq']), class:'btn btn-xs btn-danger pull-left', title: 'Actualizar precios de artículos listados' %>
      <% else %>
        <%= link_to 'Ver en PDF', articles_path(:format => :pdf), class:'btn btn-xs btn-info pull-right', title: 'PDF', target: '_blank' %>
        <%= link_to 'Actualizar precios', update_prices_path, class:'btn btn-xs btn-danger pull-left', title: 'Actualizar precios de artículos listados' %>
      <% end %>
    <% end %>
    <%= render "layouts/pagination", collection: @articles %>
<!-- When @articles collection is empty and ransack not -->
<% if @articles.length == 0 and not params[:q].nil? %>
    <div class="container">
        <h3 class="text-center">No se encontraron artículos.</h3>
    </div>
<% end %>

app/views/articles/new.html.erb
<h3 class="text-center">Nuevo artículo</h3>
<hr>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="container col-md-4 col-md-offset-4">
    <div class="container-fluid">
      <div class="panel panel-primary">
        <div class="panel-heading text-center"><b>Información del artículo</b></div>
        <div class="panel-body">
          <p>
              <strong>Nombre:</strong>
              <%= @article.name %>
          </p>
          <p>
              <strong>Código:</strong>
              <%= @article.code %>
          </p>
          <p>
              <strong>Marca:</strong>
              <%= get_mark_name(@article.mark_id) %>
          </p>
          <p>
              <strong>Descripción:</strong>
              <%= @article.description %>
          </p>
          <p>
              <strong>Precio de costo:</strong>
              $ <%= get_cost_price(@article.id) %>
          </p>
          <p>
              <strong>Historial de precios:</strong>
              <%= link_to 'Historial', article_historics_path(@article) %>
          </p>
          <p>
              <strong>Porcentaje:</strong>
              <%= @article.percentage %> %
          </p>
          <p>
              <strong>Precio venta:</strong>
              $ <%= get_final_price(@article.id) %>
          </p>
          <p>
              <strong>Categoría:</strong>
              <%= get_category_name(@article.category_id) %>
          </p>
          <p>
              <strong>Stock:</strong>
              <%= @article.stock.current_amount %>
          </p>
          <p>
              <strong>Stock mínimo:</strong>
              <%= @article.stock.minimum_amount %>
          </p>
          <p>
              <strong>Proveedores del artículo:</strong>
              <ul>
                  <% @article.providers.each do |provider| %>
                      <li><%= provider.name %></li>
                  <% end %>
              </ul>
          </p>
        </div>
      </div>
      <div class="pull-right">
        <%= link_to 'Nuevo artículo', new_article_path, class: "btn btn-primary" %>
        <%= link_to 'Editar', edit_article_path(@article), class: "btn btn-success" %>
        <%= link_to 'Artículos', articles_path, class: "btn btn-default" %>
      </div>
    </div>
</div>

app/views/articles/update_prices.html.erb
<div class="col-md-6 col-md-offset-3">
    <h3 class="text-center">Actualizar precios</h3>
    <div class="alert alert-danger">
      <strong>Advertencia</strong>: Estás por modificar el precio de costo a <strong><%= @articles.length %></strong> artículos. El precio final se calcula en base al nuevo precio de costo y al porcentaje que tenga definido cada producto previamente cargado.
    </div>
    <form class="" action="/update_prices" method="post">
        <%# Autenticación por token %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <% @articles.each do |article| %>
          <input type="hidden" name="article_id[]" value="<%= article.id %>">
        <% end %>
        <div class="form-group">
            <label for="amount_upd">Ingrese porcentaje (Ingresar valor negativo, resta al precio actual):</label>
            <input type="number" name="percentage" value="0" min="-100" max="1000" id="amount_upd" class="form-control">
        </div>
        <div class="pull-right">
            <%= link_to 'Cancelar', articles_path, class: "btn btn-default" %>
            <input type="submit" name="commit" value="Actualizar" class="btn btn-success" onclick="confirm('¿Estás seguro que quieres editar el precio a <%= @articles.length %> artículos?');">
        </div>
    </form>

</div>