config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root 'sales#new'
    
    resources :marks
    resources :categories
    resources :articles do
        resources :historics, only: [:index]
    end
    resources :providers
    resources :stocks, only: [:index]
    resources :sales, only: [:new, :create, :index, :show]
    scope 'admin', as: 'admin' do
      resources :users, except: [:new, :create]
    end
    # Update prices for providers (in mass).
    get 'update_prices', to: 'articles#update_prices'
    post 'update_prices', to: 'articles#update_prices_post'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error

    validates :name, presence: true
    validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :authorized_admin

    def index
        @q = Category.ransack(params[:q])
        @categories = @q.result.paginate(:page => params[:page]).order(:name)
    end

    def show
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = 'La categoría se ha actualizado exitosamente.'
            redirect_to @category
        else
            render :edit
        end
    end

    def update
        if @category.update(category_params)
            flash[:success] = 'La categoría se ha actualizado correctamente.'
            redirect_to return_to_previous_url
        else
            render :edit
        end
    end

    def destroy
        if @category.destroy
            flash[:success] = 'La categoría se ha eliminado exitosamente.'
        else
            flash[:alert] = 'No se puede eliminar la categoría porque tiene artículos asociados.'
        end
        redirect_to categories_url
    end

    private
        def category_params
            params.require(:category).permit(:name)
        end

        def set_category
            @category = Category.find(params[:id])
        end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
    <div class="container col-md-6 col-md-offset-3">
        <%= f.error_notification %>

        <div class="form-group">
            <%= f.input :name, required: true, autofocus: true %>
        </div>
        <div class="pull-right">
            <%= link_to 'Categorías', categories_path, class: "btn btn-default" %>
            <%= f.button :submit, class: "btn btn-success" %>
        </div>
    </div>

<% end %>

app/views/categories/edit.html.erb
<h3 class="text-center">Editar categoria</h3>
<hr>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="container-fluid">
    <%= render "layouts/search_form", search: :name_cont %>
</div>
<hr>
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Categorías</strong>
      <div class="pull-right">
        <div class="btn-right">
          <%= link_to 'Nueva categoría', new_category_path, class: "btn btn-success btn-xs" %>
        </div>
      </div>
    </div>
      <table class="table table-condensed table-bordered table-hover">
        <thead class="">
          <tr>
            <th  class="text-center"style="width: 75%"><%= sort_link(@q, :name, default_order: :desc) %></th>
            <th  class="text-center"style="width: 25%">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td class="text-center">
                  <%= link_to '', category, class:'glyphicon glyphicon-eye-open btn btn-xs btn-default', title: 'Ver' %>
                  <%= link_to '', edit_category_path(category), class:'glyphicon glyphicon-pencil btn btn-xs btn-default', title: 'Editar' %>
                  <%= link_to '', category, class:'glyphicon glyphicon-trash btn btn-xs btn-danger', title: 'Borrar', method: :delete, data: { confirm: '¿Estás seguro que quieres eliminar el elemento?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
    <br>
    <%= render "layouts/pagination", collection: @categories %>

</div>

app/views/categories/new.html.erb
<h3 class="text-center">Nueva categoria</h3>
<hr>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="container col-md-4 col-md-offset-4">
  <div class="container-fluid">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        <b class="text-center">Información de categoria</b>
      </div>
      <div class="panel-body">
        <p>
          <strong>Nombre:</strong>
          <%= @category.name %>
        </p>

      </div>
    </div>
    <div class="pull-right">
      <%= link_to 'Nueva categoría', new_category_path, class: "btn btn-primary" %>
      <%= link_to 'Editar', edit_category_path(@category), class: "btn btn-success" %>
      <%= link_to 'Categorías', categories_path, class: "btn btn-default" %>
    </div>
  </div>

</div>