config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root 'sales#new'
    
    resources :marks
    resources :categories
    resources :articles do
        resources :historics, only: [:index]
    end
    resources :providers
    resources :stocks, only: [:index]
    resources :sales, only: [:new, :create, :index, :show]
    scope 'admin', as: 'admin' do
      resources :users, except: [:new, :create]
    end
    # Update prices for providers (in mass).
    get 'update_prices', to: 'articles#update_prices'
    post 'update_prices', to: 'articles#update_prices_post'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :category
    belongs_to :mark
    has_one :stock, inverse_of: :article, dependent: :destroy
    has_many :historics, dependent: :destroy, inverse_of: :article
    has_many :sale_lines, dependent: :restrict_with_error
    has_many :sales, through: :sale_lines
    has_many :article_providers, dependent: :destroy, inverse_of: :article
    has_many :providers, through: :article_providers

    accepts_nested_attributes_for :article_providers, allow_destroy: true
    accepts_nested_attributes_for :stock, reject_if: :all_blank
    validates_presence_of :stock
    # accepts_nested_attributes_for :historics, reject_if: :all_blank
    # validates_presence_of :historics, on: :create
    validates :code, :name, :cost_price, :percentage, :mark_id, :category_id, presence: true
    validates :cost_price, numericality: { greater_than_or_equal_to: 0 }
    validates :final_price, numericality: { greater_than_or_equal_to: 0 }
    validates :percentage, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    validates :code, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates_uniqueness_of :code

    def create_historic(new_cost_price)
        self.historics.create({cost_price: new_cost_price})
    end

    def last_update_price()
      self.historics.last.created_at
    end

    private
        # Convierto codigo en string para poder buscar en Ransack usando LIKE de SQL.
        ransacker :code do
            Arel.sql("CONVERT(#{table_name}.code, CHAR(14))")
        end

end

app/models/article_provider.rb
class ArticleProvider < ApplicationRecord
    belongs_to :article, inverse_of: :article_providers
    belongs_to :provider
    validates_presence_of :article
    validates :provider_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error

    validates :name, presence: true
    validates_uniqueness_of :name
end

app/models/historic.rb
class Historic < ApplicationRecord
    belongs_to :article, inverse_of: :historics

    validates_presence_of :article
    validates :cost_price, presence: true
    validates :cost_price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/mark.rb
class Mark < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error

    validates :name, presence: true
    validates_uniqueness_of :name
end

app/models/provider.rb
class Provider < ApplicationRecord
    has_many :article_providers, dependent: :restrict_with_error
    has_many :articles, through: :article_providers

    validates :name, presence: true
    validates_uniqueness_of :name
end

app/models/sale.rb
class Sale < ApplicationRecord
    has_many :sale_lines, inverse_of: :sale
    has_many :articles, through: :sale_lines

    validates :sale_lines, presence: true
    accepts_nested_attributes_for :sale_lines
    validates :total_price, numericality: { greater_than_or_equal_to: 0 }, presence: true

    private
        ransacker :date_created_at do
            Arel.sql("date(sales.created_at)")
        end
end

app/models/sale_line.rb
class SaleLine < ApplicationRecord
    belongs_to :sale, inverse_of: :sale_lines
    belongs_to :article

    validates_presence_of :sale
    validates :article_id, :article_amount, :article_final_price_unit, presence: true
    validates :article_amount, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    validates :article_final_price_unit, numericality: { greater_than_or_equal_to: 0 }
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :article, inverse_of: :stock
    validates_presence_of :article

    validates :current_amount, :minimum_amount, presence: true
    validates :current_amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :minimum_amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :timeoutable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]

  #def destroy
  #  update_attributes(deactivated: true) unless deactivated
  #end

  def active_for_authentication?
    super && !deactivated
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def get_providers(article_id)
        Article.find(article_id).providers
    end

    def get_category_name(category_id)
        Category.find(category_id).name
    end

    def get_mark_name(mark_id)
        Mark.find(mark_id).name
    end

    def get_final_price(article_id)
      if not article_id.nil?
        ActionController::Base.helpers.number_with_precision(Article.find(article_id).final_price, precision: 2, separator: '.')
      end
    end

    def get_cost_price(article_id)
      if not article_id.nil?
        ActionController::Base.helpers.number_with_precision(Article.find(article_id).cost_price, precision: 2, separator: '.')
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/historics_helper.rb
module HistoricsHelper
  def get_historic_cost_price(historic_id)
    ActionController::Base.helpers.number_with_precision(Historic.find(historic_id).cost_price, precision: 2, separator: '.')
  end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
    def get_article(article_id)
        Article.find(article_id)
    end

    def get_difference(stock)
        stock.current_amount - stock.minimum_amount
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if flash[:success] %>
  <div class="alert alert-success dismissable text-center" role="alert">
      <span><%= flash[:success] %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
  </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-danger text-center dismissable text-center" role="alert">
        <span><%= flash[:alert] %></span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <a class="navbar-brand" href="/">Kiosco</a>
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Inicio", root_path %></li>
        <% if user_signed_in? %>
          <% if current_user.try(:admin?) %>
            <li class="<%= 'active' if current_page?(articles_path) %>"><%= link_to "Artículos", articles_path %></li>
            <li class="<%= 'active' if current_page?(categories_path) %>"><%= link_to "Categorías", categories_path %></li>
            <li class="<%= 'active' if current_page?(providers_path) %>"><%= link_to "Proveedores", providers_path %></li>
            <li class="<%= 'active' if current_page?(marks_path) %>"><%= link_to "Marcas", marks_path %></li>
          <% end %>
          <li class="<%= 'active' if current_page?(stocks_path) %>"><%= link_to "Stock", stocks_path %></li>
          <% if current_user.try(:admin?) %>
            <li class="<%= 'active' if current_page?(sales_path) %>"><%= link_to "Listar ventas", sales_path %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><a href="<%= admin_users_path %>">Listar usuarios</a></li>
                <% end %>
                <li><a href="<%= edit_user_registration_path %>">Editar cuenta</a></li>
                <li><%= link_to('Cerrar sesión', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
          <% else %>
            <%= link_to('Iniciar sesión', new_user_session_path)  %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_pagination.html.erb
<div class="text-center">
    <%= will_paginate collection, previous_label: :Anterior, next_label: :Siguiente, renderer: BootstrapPagination::Rails %>
</div>

app/views/layouts/_search_form.html.erb
<div class="container-fluid pull-right">
    <div class="form-inline">
        <%= search_form_for @q do |f| %>
        <%= f.text_field search, class: "form-control", placeholder: "Buscar", onclick: 'this.select();' %>
        <%= f.submit "Buscar", class: "btn btn-default" %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de ventas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 60px;">
      <%= render "layouts/navbar" %>
      <div class="container-fluid">
          <%= render "layouts/alerts" %>
          <%= yield %>
      </div>
      <footer class="footer" style="padding: 5px;">
          <div class="container-fluid">
          </div>
      </footer>
  </body>


</html>